__version__: 1.0.3
transform:
  __class_fullname__: Compose
  additional_targets:
    image1: image
    mask1: mask
  bbox_params: null
  keypoint_params: null
  p: 1.0
  transforms:
  - __class_fullname__: Resize
    always_apply: true
    height: 540
    interpolation: 1
    p: 1
    width: 540
  - __class_fullname__: RandomCrop
    always_apply: true
    height: 512
    p: 1.0
    width: 512
  - __class_fullname__: HorizontalFlip
    always_apply: false
    p: 0.3
  - __class_fullname__: VerticalFlip
    always_apply: false
    p: 0.3
  - __class_fullname__: OneOf
    p: 0.3
    transforms:
    - __class_fullname__: RandomGamma
      always_apply: false
      eps: null
      gamma_limit:
      - 80
      - 120
      p: 0.5
    - __class_fullname__: RandomBrightnessContrast
      always_apply: false
      brightness_by_max: true
      brightness_limit:
      - -0.2
      - 0.2
      contrast_limit:
      - -0.2
      - 0.2
      p: 0.5
  - __class_fullname__: OneOf
    p: 0.2
    transforms:
    - __class_fullname__: ElasticTransform
      alpha: 120
      alpha_affine: 3.5999999999999996
      always_apply: false
      approximate: false
      border_mode: 4
      interpolation: 1
      mask_value: null
      p: 0.5
      sigma: 6.0
      value: null
    - __class_fullname__: GridDistortion
      always_apply: false
      border_mode: 4
      distort_limit:
      - -0.3
      - 0.3
      interpolation: 1
      mask_value: null
      num_steps: 5
      p: 0.5
      value: null
  - __class_fullname__: ShiftScaleRotate
    always_apply: false
    border_mode: 4
    interpolation: 1
    mask_value: null
    p: 0.5
    rotate_limit:
    - -30
    - 30
    scale_limit:
    - -0.09999999999999998
    - 0.10000000000000009
    shift_limit_x:
    - -0.0625
    - 0.0625
    shift_limit_y:
    - -0.0625
    - 0.0625
    value: null
  - __class_fullname__: ToTensorV2
    always_apply: true
    p: 1.0
    transpose_mask: false
